---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: express-api
  namespace: <YOUR_NAMESPACE>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: asia.gcr.io/<PROJECT_ID>/demo/express-api:1.0.0
        # resources:
        #   limits:  
        #     memory: 200Mi
        #   requests:
        #     memory: 128Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_CONFIGMAP
          valueFrom:
              configMapKeyRef:
                name: express-api-config
                key: value
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: express-api-secret
              key: password

