---
apiVersion: v1
kind: Service
metadata:
  name: express-api
  namespace: <YOUR_NAMESPACE>
spec:
  ports:
  - port: 3000
    targetPort: 3000
  #   nodePort: 31001
  # type : NodePort
  selector:
    app: express-api